services:
  app:
    build: .
    container_name: alxarafe-test
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    tty: true
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
