<?php
require __DIR__ . '/../vendor/autoload.php';

use Alxarafe\ResourceTest\DemoController;
use Alxarafe\ResourceController\Render\DefaultRenderer;

// Initialize a memory SQLite database for PDO
try {
    $pdo = new \PDO('sqlite::memory:');
} catch (\PDOException $e) {
    // Fallback for environments without pdo_sqlite
    $pdo = new class extends \PDO {
        public function __construct() {}
        public function prepare($query, $options = []): \PDOStatement|false {
            return new class extends \PDOStatement {
                public function execute($params = null): bool { return true; }
                public function fetch($mode = \PDO::FETCH_BOTH, $cursorOrientation = \PDO::FETCH_ORI_NEXT, $cursorOffset = 0): mixed { return []; }
            };
        }
        public function query($query, $mode = \PDO::FETCH_DEFAULT, ...$fetch_mode_args): \PDOStatement|false {
            return new class extends \PDOStatement {
                public function execute($params = null): bool { return true; }
                public function fetch($mode = \PDO::FETCH_BOTH, $cursorOrientation = \PDO::FETCH_ORI_NEXT, $cursorOffset = 0): mixed { return []; }
            };
        }
    };
}

// Instantiate the controller
$controller = new DemoController($pdo);

// Extract the UI metadata generated by resource-controller
$config = $controller->getViewDescriptor();

// Setup the built-in renderer (consolidated from resource-html)
$renderer = new DefaultRenderer(__DIR__ . '/../views');

// Render the layout
echo $renderer->render('layout', [
    'title' => 'Declarative UI with Alxarafe',
    'config' => $config
]);
