<?php
require __DIR__ . '/../vendor/autoload.php';

use Alxarafe\ResourceTest\DemoController;
use Alxarafe\ResourceHtml\HtmlRenderer;

// Initialize a memory SQLite database for PDO
$pdo = new \PDO('sqlite::memory:');

// Instantiate the controller
$controller = new DemoController($pdo);

// Extract the UI metadata generated by resource-controller
$config = $controller->getViewDescriptor();

// Setup pure PHP HTML renderer
$renderer = new HtmlRenderer(__DIR__ . '/../views');

// Render the layout
echo $renderer->render('layout', [
    'title' => 'Declarative UI with resource-html',
    'config' => $config
]);
